// <auto-generated />
using System;
using CatBD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatBD.Migrations
{
    [DbContext(typeof(ApplicationDBcontext))]
    [Migration("20230510145207_BreedSart")]
    partial class BreedSart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatBD.BreedCharacteristics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adaptabiliti")
                        .HasColumnType("integer");

                    b.Property<int>("AttachmentTofamily")
                        .HasColumnType("integer");

                    b.Property<int>("FriendlinessForChildren")
                        .HasColumnType("integer");

                    b.Property<int>("FriendlyToDogs")
                        .HasColumnType("integer");

                    b.Property<int>("GameActivity")
                        .HasColumnType("integer");

                    b.Property<int>("GeneralHealth")
                        .HasColumnType("integer");

                    b.Property<int>("HairLoss")
                        .HasColumnType("integer");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<int>("LoveForMeow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("breedCharacteristics");
                });

            modelBuilder.Entity("CatBD.Famyly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FamylyName")
                        .HasColumnType("text");

                    b.Property<int?>("IdCharacter")
                        .HasColumnType("integer");

                    b.Property<int?>("IdInfo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("famylies");
                });

            modelBuilder.Entity("CatBD.InformationAboutTheBreed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LifeExpectancy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lifestyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight_kg")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("infoAboutTheBreeds");
                });
#pragma warning restore 612, 618
        }
    }
}
